---

- set_fact:
    script_dir: /tmp/helm

- name: remove /usr/local/bin/helm
  file:
    path: "/usr/local/bin/helm"
    state: absent
  when: inventory_hostname in groups['master_nodes']
  become: true

- name: remove {{ script_dir }}
  file:
    path: "{{ script_dir }}"
    state: absent
  when: inventory_hostname in groups['master_nodes']
