server: https://{{ hostvars[groups['master_nodes'][0]]['ansible_default_ipv4']['address'] }}:{{ k8s.rke2.config.port }}
token: {{ k8s.rke2.config.token }}
node-name: {{ inventory_hostname }}
cni: multus,canal
cluster-cidr: 10.42.0.0/16
service-cidr: 10.42.0.0/16
kubelet-arg:
- --allowed-unsafe-sysctls=net.*
pause-image: k8s.gcr.io/pause:3.3
kube-proxy-arg:
- --metrics-bind-address=0.0.0.0:10249
- --proxy-mode=ipvs
kube-apiserver-arg:
- --service-node-port-range=2000-36767
