---

- name: delete {{ ansible_env.HOME }}/.kube
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: delete /usr/local/bin/kubectl
  file:
    path: "/usr/local/bin/kubectl"
    state: absent
  when: inventory_hostname in groups['master_nodes']
  become: true

- set_fact:
    script_dir: /tmp/rke2

# - name: delete /etc/rancher/rke2/config.yaml
#   file:
#     path: /etc/rancher/rke2/config.yaml
#     state: absent
#   become: true

- name: uninstall rke2 masters/workers
  command: "/usr/local/bin/rke2-uninstall.sh"
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2.version }}"
  become: true
  ignore_errors: yes

- name: remove {{ script_dir }}
  file:
    path: "{{ script_dir }}"
    state: absent
